/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConsoleRouteRouteImport } from './routes/console/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ConsoleIndexRouteImport } from './routes/console/index'
import { Route as ConsoleProjectIdRouteRouteImport } from './routes/console/$projectId/route'
import { Route as DocsIndexRouteImport } from './routes/docs/index'
import { Route as DocsApiRouteImport } from './routes/docs/api'
import { Route as DocsApiKeysRouteImport } from './routes/docs/api-keys'
import { Route as DocsDeliveryRouteImport } from './routes/docs/delivery'
import { Route as DocsFrameworksRouteImport } from './routes/docs/frameworks'
import { Route as DocsGoSdkRouteImport } from './routes/docs/go-sdk'
import { Route as DocsJavascriptSdkRouteImport } from './routes/docs/javascript-sdk'
import { Route as DocsPythonSdkRouteImport } from './routes/docs/python-sdk'
import { Route as DocsReactSdkRouteImport } from './routes/docs/react-sdk'
import { Route as DocsUploadingRouteImport } from './routes/docs/uploading'
import { Route as DocsWebhooksRouteImport } from './routes/docs/webhooks'
import { Route as V1UploadTokensRouteImport } from './routes/v1/upload-tokens'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ConsoleProjectIdIndexRouteImport } from './routes/console/$projectId/index'
import { Route as ConsoleProjectIdActivityRouteImport } from './routes/console/$projectId/activity'
import { Route as ConsoleProjectIdFilesRouteImport } from './routes/console/$projectId/files'
import { Route as ConsoleProjectIdKeysRouteImport } from './routes/console/$projectId/keys'
import { Route as ConsoleProjectIdPlaygroundRouteImport } from './routes/console/$projectId/playground'
import { Route as ConsoleProjectIdSettingsRouteRouteImport } from './routes/console/$projectId/settings/route'
import { Route as ConsoleProjectIdSettingsRouteImport } from './routes/console/$projectId/settings'
import { Route as ConsoleProjectIdWebhooksRouteImport } from './routes/console/$projectId/webhooks'
import { Route as FNamespaceSplatRouteImport } from './routes/f/$namespace/$'
import { Route as V1FilesSplatRouteImport } from './routes/v1/files/$'
import { Route as V1UploadsUploadIdRouteImport } from './routes/v1/uploads/$uploadId'
import { Route as ConsoleProjectIdSettingsIndexRouteImport } from './routes/console/$projectId/settings/index'
import { Route as ConsoleProjectIdWebhooksWebhookIdRouteImport } from './routes/console/$projectId/webhooks/$webhookId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleRouteRoute = ConsoleRouteRouteImport.update({
  id: '/console',
  path: '/console',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleIndexRoute = ConsoleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ConsoleRouteRoute,
} as any)
const ConsoleProjectIdRouteRoute = ConsoleProjectIdRouteRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => ConsoleRouteRoute,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsApiRoute = DocsApiRouteImport.update({
  id: '/docs/api',
  path: '/docs/api',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsApiKeysRoute = DocsApiKeysRouteImport.update({
  id: '/docs/api-keys',
  path: '/docs/api-keys',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsDeliveryRoute = DocsDeliveryRouteImport.update({
  id: '/docs/delivery',
  path: '/docs/delivery',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsFrameworksRoute = DocsFrameworksRouteImport.update({
  id: '/docs/frameworks',
  path: '/docs/frameworks',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsGoSdkRoute = DocsGoSdkRouteImport.update({
  id: '/docs/go-sdk',
  path: '/docs/go-sdk',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsJavascriptSdkRoute = DocsJavascriptSdkRouteImport.update({
  id: '/docs/javascript-sdk',
  path: '/docs/javascript-sdk',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsPythonSdkRoute = DocsPythonSdkRouteImport.update({
  id: '/docs/python-sdk',
  path: '/docs/python-sdk',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsReactSdkRoute = DocsReactSdkRouteImport.update({
  id: '/docs/react-sdk',
  path: '/docs/react-sdk',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsUploadingRoute = DocsUploadingRouteImport.update({
  id: '/docs/uploading',
  path: '/docs/uploading',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsWebhooksRoute = DocsWebhooksRouteImport.update({
  id: '/docs/webhooks',
  path: '/docs/webhooks',
  getParentRoute: () => rootRouteImport,
} as any)
const V1UploadTokensRoute = V1UploadTokensRouteImport.update({
  id: '/v1/upload-tokens',
  path: '/v1/upload-tokens',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleProjectIdIndexRoute = ConsoleProjectIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ConsoleProjectIdRouteRoute,
} as any)
const ConsoleProjectIdActivityRoute =
  ConsoleProjectIdActivityRouteImport.update({
    id: '/activity',
    path: '/activity',
    getParentRoute: () => ConsoleProjectIdRouteRoute,
  } as any)
const ConsoleProjectIdFilesRoute = ConsoleProjectIdFilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => ConsoleProjectIdRouteRoute,
} as any)
const ConsoleProjectIdKeysRoute = ConsoleProjectIdKeysRouteImport.update({
  id: '/keys',
  path: '/keys',
  getParentRoute: () => ConsoleProjectIdRouteRoute,
} as any)
const ConsoleProjectIdPlaygroundRoute =
  ConsoleProjectIdPlaygroundRouteImport.update({
    id: '/playground',
    path: '/playground',
    getParentRoute: () => ConsoleProjectIdRouteRoute,
  } as any)
const ConsoleProjectIdSettingsRouteRoute =
  ConsoleProjectIdSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => ConsoleProjectIdRouteRoute,
  } as any)
const ConsoleProjectIdSettingsRoute =
  ConsoleProjectIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => ConsoleProjectIdRouteRoute,
  } as any)
const ConsoleProjectIdWebhooksRoute =
  ConsoleProjectIdWebhooksRouteImport.update({
    id: '/webhooks',
    path: '/webhooks',
    getParentRoute: () => ConsoleProjectIdRouteRoute,
  } as any)
const FNamespaceSplatRoute = FNamespaceSplatRouteImport.update({
  id: '/f/$namespace/$',
  path: '/f/$namespace/$',
  getParentRoute: () => rootRouteImport,
} as any)
const V1FilesSplatRoute = V1FilesSplatRouteImport.update({
  id: '/v1/files/$',
  path: '/v1/files/$',
  getParentRoute: () => rootRouteImport,
} as any)
const V1UploadsUploadIdRoute = V1UploadsUploadIdRouteImport.update({
  id: '/v1/uploads/$uploadId',
  path: '/v1/uploads/$uploadId',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleProjectIdSettingsIndexRoute =
  ConsoleProjectIdSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ConsoleProjectIdSettingsRoute,
  } as any)
const ConsoleProjectIdWebhooksWebhookIdRoute =
  ConsoleProjectIdWebhooksWebhookIdRouteImport.update({
    id: '/$webhookId',
    path: '/$webhookId',
    getParentRoute: () => ConsoleProjectIdWebhooksRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/console': typeof ConsoleRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/console/$projectId': typeof ConsoleProjectIdRouteRouteWithChildren
  '/docs/api': typeof DocsApiRoute
  '/docs/api-keys': typeof DocsApiKeysRoute
  '/docs/delivery': typeof DocsDeliveryRoute
  '/docs/frameworks': typeof DocsFrameworksRoute
  '/docs/go-sdk': typeof DocsGoSdkRoute
  '/docs/javascript-sdk': typeof DocsJavascriptSdkRoute
  '/docs/python-sdk': typeof DocsPythonSdkRoute
  '/docs/react-sdk': typeof DocsReactSdkRoute
  '/docs/uploading': typeof DocsUploadingRoute
  '/docs/webhooks': typeof DocsWebhooksRoute
  '/v1/upload-tokens': typeof V1UploadTokensRoute
  '/console/': typeof ConsoleIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/console/$projectId/settings': typeof ConsoleProjectIdSettingsRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/console/$projectId/activity': typeof ConsoleProjectIdActivityRoute
  '/console/$projectId/files': typeof ConsoleProjectIdFilesRoute
  '/console/$projectId/keys': typeof ConsoleProjectIdKeysRoute
  '/console/$projectId/playground': typeof ConsoleProjectIdPlaygroundRoute
  '/console/$projectId/webhooks': typeof ConsoleProjectIdWebhooksRouteWithChildren
  '/f/$namespace/$': typeof FNamespaceSplatRoute
  '/v1/files/$': typeof V1FilesSplatRoute
  '/v1/uploads/$uploadId': typeof V1UploadsUploadIdRoute
  '/console/$projectId/': typeof ConsoleProjectIdIndexRoute
  '/console/$projectId/webhooks/$webhookId': typeof ConsoleProjectIdWebhooksWebhookIdRoute
  '/console/$projectId/settings/': typeof ConsoleProjectIdSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/docs/api': typeof DocsApiRoute
  '/docs/api-keys': typeof DocsApiKeysRoute
  '/docs/delivery': typeof DocsDeliveryRoute
  '/docs/frameworks': typeof DocsFrameworksRoute
  '/docs/go-sdk': typeof DocsGoSdkRoute
  '/docs/javascript-sdk': typeof DocsJavascriptSdkRoute
  '/docs/python-sdk': typeof DocsPythonSdkRoute
  '/docs/react-sdk': typeof DocsReactSdkRoute
  '/docs/uploading': typeof DocsUploadingRoute
  '/docs/webhooks': typeof DocsWebhooksRoute
  '/v1/upload-tokens': typeof V1UploadTokensRoute
  '/console': typeof ConsoleIndexRoute
  '/docs': typeof DocsIndexRoute
  '/console/$projectId/settings': typeof ConsoleProjectIdSettingsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/console/$projectId/activity': typeof ConsoleProjectIdActivityRoute
  '/console/$projectId/files': typeof ConsoleProjectIdFilesRoute
  '/console/$projectId/keys': typeof ConsoleProjectIdKeysRoute
  '/console/$projectId/playground': typeof ConsoleProjectIdPlaygroundRoute
  '/console/$projectId/webhooks': typeof ConsoleProjectIdWebhooksRouteWithChildren
  '/f/$namespace/$': typeof FNamespaceSplatRoute
  '/v1/files/$': typeof V1FilesSplatRoute
  '/v1/uploads/$uploadId': typeof V1UploadsUploadIdRoute
  '/console/$projectId': typeof ConsoleProjectIdIndexRoute
  '/console/$projectId/webhooks/$webhookId': typeof ConsoleProjectIdWebhooksWebhookIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/console': typeof ConsoleRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/console/$projectId': typeof ConsoleProjectIdRouteRouteWithChildren
  '/docs/api': typeof DocsApiRoute
  '/docs/api-keys': typeof DocsApiKeysRoute
  '/docs/delivery': typeof DocsDeliveryRoute
  '/docs/frameworks': typeof DocsFrameworksRoute
  '/docs/go-sdk': typeof DocsGoSdkRoute
  '/docs/javascript-sdk': typeof DocsJavascriptSdkRoute
  '/docs/python-sdk': typeof DocsPythonSdkRoute
  '/docs/react-sdk': typeof DocsReactSdkRoute
  '/docs/uploading': typeof DocsUploadingRoute
  '/docs/webhooks': typeof DocsWebhooksRoute
  '/v1/upload-tokens': typeof V1UploadTokensRoute
  '/console/': typeof ConsoleIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/console/$projectId/settings': typeof ConsoleProjectIdSettingsRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/console/$projectId/activity': typeof ConsoleProjectIdActivityRoute
  '/console/$projectId/files': typeof ConsoleProjectIdFilesRoute
  '/console/$projectId/keys': typeof ConsoleProjectIdKeysRoute
  '/console/$projectId/playground': typeof ConsoleProjectIdPlaygroundRoute
  '/console/$projectId/webhooks': typeof ConsoleProjectIdWebhooksRouteWithChildren
  '/f/$namespace/$': typeof FNamespaceSplatRoute
  '/v1/files/$': typeof V1FilesSplatRoute
  '/v1/uploads/$uploadId': typeof V1UploadsUploadIdRoute
  '/console/$projectId/': typeof ConsoleProjectIdIndexRoute
  '/console/$projectId/webhooks/$webhookId': typeof ConsoleProjectIdWebhooksWebhookIdRoute
  '/console/$projectId/settings/': typeof ConsoleProjectIdSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/console'
    | '/login'
    | '/pricing'
    | '/console/$projectId'
    | '/docs/api'
    | '/docs/api-keys'
    | '/docs/delivery'
    | '/docs/frameworks'
    | '/docs/go-sdk'
    | '/docs/javascript-sdk'
    | '/docs/python-sdk'
    | '/docs/react-sdk'
    | '/docs/uploading'
    | '/docs/webhooks'
    | '/v1/upload-tokens'
    | '/console/'
    | '/docs/'
    | '/console/$projectId/settings'
    | '/api/auth/$'
    | '/console/$projectId/activity'
    | '/console/$projectId/files'
    | '/console/$projectId/keys'
    | '/console/$projectId/playground'
    | '/console/$projectId/webhooks'
    | '/f/$namespace/$'
    | '/v1/files/$'
    | '/v1/uploads/$uploadId'
    | '/console/$projectId/'
    | '/console/$projectId/webhooks/$webhookId'
    | '/console/$projectId/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/pricing'
    | '/docs/api'
    | '/docs/api-keys'
    | '/docs/delivery'
    | '/docs/frameworks'
    | '/docs/go-sdk'
    | '/docs/javascript-sdk'
    | '/docs/python-sdk'
    | '/docs/react-sdk'
    | '/docs/uploading'
    | '/docs/webhooks'
    | '/v1/upload-tokens'
    | '/console'
    | '/docs'
    | '/console/$projectId/settings'
    | '/api/auth/$'
    | '/console/$projectId/activity'
    | '/console/$projectId/files'
    | '/console/$projectId/keys'
    | '/console/$projectId/playground'
    | '/console/$projectId/webhooks'
    | '/f/$namespace/$'
    | '/v1/files/$'
    | '/v1/uploads/$uploadId'
    | '/console/$projectId'
    | '/console/$projectId/webhooks/$webhookId'
  id:
    | '__root__'
    | '/'
    | '/console'
    | '/login'
    | '/pricing'
    | '/console/$projectId'
    | '/docs/api'
    | '/docs/api-keys'
    | '/docs/delivery'
    | '/docs/frameworks'
    | '/docs/go-sdk'
    | '/docs/javascript-sdk'
    | '/docs/python-sdk'
    | '/docs/react-sdk'
    | '/docs/uploading'
    | '/docs/webhooks'
    | '/v1/upload-tokens'
    | '/console/'
    | '/docs/'
    | '/console/$projectId/settings'
    | '/api/auth/$'
    | '/console/$projectId/activity'
    | '/console/$projectId/files'
    | '/console/$projectId/keys'
    | '/console/$projectId/playground'
    | '/console/$projectId/webhooks'
    | '/f/$namespace/$'
    | '/v1/files/$'
    | '/v1/uploads/$uploadId'
    | '/console/$projectId/'
    | '/console/$projectId/webhooks/$webhookId'
    | '/console/$projectId/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConsoleRouteRoute: typeof ConsoleRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  DocsApiRoute: typeof DocsApiRoute
  DocsApiKeysRoute: typeof DocsApiKeysRoute
  DocsDeliveryRoute: typeof DocsDeliveryRoute
  DocsFrameworksRoute: typeof DocsFrameworksRoute
  DocsGoSdkRoute: typeof DocsGoSdkRoute
  DocsJavascriptSdkRoute: typeof DocsJavascriptSdkRoute
  DocsPythonSdkRoute: typeof DocsPythonSdkRoute
  DocsReactSdkRoute: typeof DocsReactSdkRoute
  DocsUploadingRoute: typeof DocsUploadingRoute
  DocsWebhooksRoute: typeof DocsWebhooksRoute
  V1UploadTokensRoute: typeof V1UploadTokensRoute
  DocsIndexRoute: typeof DocsIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  FNamespaceSplatRoute: typeof FNamespaceSplatRoute
  V1FilesSplatRoute: typeof V1FilesSplatRoute
  V1UploadsUploadIdRoute: typeof V1UploadsUploadIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console': {
      id: '/console'
      path: '/console'
      fullPath: '/console'
      preLoaderRoute: typeof ConsoleRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console/': {
      id: '/console/'
      path: '/'
      fullPath: '/console/'
      preLoaderRoute: typeof ConsoleIndexRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/console/$projectId': {
      id: '/console/$projectId'
      path: '/$projectId'
      fullPath: '/console/$projectId'
      preLoaderRoute: typeof ConsoleProjectIdRouteRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/docs/': {
      id: '/docs/'
      path: '/docs'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/api': {
      id: '/docs/api'
      path: '/docs/api'
      fullPath: '/docs/api'
      preLoaderRoute: typeof DocsApiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/api-keys': {
      id: '/docs/api-keys'
      path: '/docs/api-keys'
      fullPath: '/docs/api-keys'
      preLoaderRoute: typeof DocsApiKeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/delivery': {
      id: '/docs/delivery'
      path: '/docs/delivery'
      fullPath: '/docs/delivery'
      preLoaderRoute: typeof DocsDeliveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/frameworks': {
      id: '/docs/frameworks'
      path: '/docs/frameworks'
      fullPath: '/docs/frameworks'
      preLoaderRoute: typeof DocsFrameworksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/go-sdk': {
      id: '/docs/go-sdk'
      path: '/docs/go-sdk'
      fullPath: '/docs/go-sdk'
      preLoaderRoute: typeof DocsGoSdkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/javascript-sdk': {
      id: '/docs/javascript-sdk'
      path: '/docs/javascript-sdk'
      fullPath: '/docs/javascript-sdk'
      preLoaderRoute: typeof DocsJavascriptSdkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/python-sdk': {
      id: '/docs/python-sdk'
      path: '/docs/python-sdk'
      fullPath: '/docs/python-sdk'
      preLoaderRoute: typeof DocsPythonSdkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/react-sdk': {
      id: '/docs/react-sdk'
      path: '/docs/react-sdk'
      fullPath: '/docs/react-sdk'
      preLoaderRoute: typeof DocsReactSdkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/uploading': {
      id: '/docs/uploading'
      path: '/docs/uploading'
      fullPath: '/docs/uploading'
      preLoaderRoute: typeof DocsUploadingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/webhooks': {
      id: '/docs/webhooks'
      path: '/docs/webhooks'
      fullPath: '/docs/webhooks'
      preLoaderRoute: typeof DocsWebhooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/upload-tokens': {
      id: '/v1/upload-tokens'
      path: '/v1/upload-tokens'
      fullPath: '/v1/upload-tokens'
      preLoaderRoute: typeof V1UploadTokensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console/$projectId/': {
      id: '/console/$projectId/'
      path: '/'
      fullPath: '/console/$projectId/'
      preLoaderRoute: typeof ConsoleProjectIdIndexRouteImport
      parentRoute: typeof ConsoleProjectIdRouteRoute
    }
    '/console/$projectId/activity': {
      id: '/console/$projectId/activity'
      path: '/activity'
      fullPath: '/console/$projectId/activity'
      preLoaderRoute: typeof ConsoleProjectIdActivityRouteImport
      parentRoute: typeof ConsoleProjectIdRouteRoute
    }
    '/console/$projectId/files': {
      id: '/console/$projectId/files'
      path: '/files'
      fullPath: '/console/$projectId/files'
      preLoaderRoute: typeof ConsoleProjectIdFilesRouteImport
      parentRoute: typeof ConsoleProjectIdRouteRoute
    }
    '/console/$projectId/keys': {
      id: '/console/$projectId/keys'
      path: '/keys'
      fullPath: '/console/$projectId/keys'
      preLoaderRoute: typeof ConsoleProjectIdKeysRouteImport
      parentRoute: typeof ConsoleProjectIdRouteRoute
    }
    '/console/$projectId/playground': {
      id: '/console/$projectId/playground'
      path: '/playground'
      fullPath: '/console/$projectId/playground'
      preLoaderRoute: typeof ConsoleProjectIdPlaygroundRouteImport
      parentRoute: typeof ConsoleProjectIdRouteRoute
    }
    '/console/$projectId/settings': {
      id: '/console/$projectId/settings'
      path: '/settings'
      fullPath: '/console/$projectId/settings'
      preLoaderRoute: typeof ConsoleProjectIdSettingsRouteRouteImport
      parentRoute: typeof ConsoleProjectIdRouteRoute
    }
    '/console/$projectId/settings': {
      id: '/console/$projectId/settings'
      path: '/settings'
      fullPath: '/console/$projectId/settings'
      preLoaderRoute: typeof ConsoleProjectIdSettingsRouteImport
      parentRoute: typeof ConsoleProjectIdRouteRoute
    }
    '/console/$projectId/webhooks': {
      id: '/console/$projectId/webhooks'
      path: '/webhooks'
      fullPath: '/console/$projectId/webhooks'
      preLoaderRoute: typeof ConsoleProjectIdWebhooksRouteImport
      parentRoute: typeof ConsoleProjectIdRouteRoute
    }
    '/f/$namespace/$': {
      id: '/f/$namespace/$'
      path: '/f/$namespace/$'
      fullPath: '/f/$namespace/$'
      preLoaderRoute: typeof FNamespaceSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/files/$': {
      id: '/v1/files/$'
      path: '/v1/files/$'
      fullPath: '/v1/files/$'
      preLoaderRoute: typeof V1FilesSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/uploads/$uploadId': {
      id: '/v1/uploads/$uploadId'
      path: '/v1/uploads/$uploadId'
      fullPath: '/v1/uploads/$uploadId'
      preLoaderRoute: typeof V1UploadsUploadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console/$projectId/settings/': {
      id: '/console/$projectId/settings/'
      path: '/'
      fullPath: '/console/$projectId/settings/'
      preLoaderRoute: typeof ConsoleProjectIdSettingsIndexRouteImport
      parentRoute: typeof ConsoleProjectIdSettingsRoute
    }
    '/console/$projectId/webhooks/$webhookId': {
      id: '/console/$projectId/webhooks/$webhookId'
      path: '/$webhookId'
      fullPath: '/console/$projectId/webhooks/$webhookId'
      preLoaderRoute: typeof ConsoleProjectIdWebhooksWebhookIdRouteImport
      parentRoute: typeof ConsoleProjectIdWebhooksRoute
    }
  }
}

interface ConsoleProjectIdSettingsRouteChildren {
  ConsoleProjectIdSettingsIndexRoute: typeof ConsoleProjectIdSettingsIndexRoute
}

const ConsoleProjectIdSettingsRouteChildren: ConsoleProjectIdSettingsRouteChildren =
  {
    ConsoleProjectIdSettingsIndexRoute: ConsoleProjectIdSettingsIndexRoute,
  }

const ConsoleProjectIdSettingsRouteWithChildren =
  ConsoleProjectIdSettingsRoute._addFileChildren(
    ConsoleProjectIdSettingsRouteChildren,
  )

interface ConsoleProjectIdWebhooksRouteChildren {
  ConsoleProjectIdWebhooksWebhookIdRoute: typeof ConsoleProjectIdWebhooksWebhookIdRoute
}

const ConsoleProjectIdWebhooksRouteChildren: ConsoleProjectIdWebhooksRouteChildren =
  {
    ConsoleProjectIdWebhooksWebhookIdRoute:
      ConsoleProjectIdWebhooksWebhookIdRoute,
  }

const ConsoleProjectIdWebhooksRouteWithChildren =
  ConsoleProjectIdWebhooksRoute._addFileChildren(
    ConsoleProjectIdWebhooksRouteChildren,
  )

interface ConsoleProjectIdRouteRouteChildren {
  ConsoleProjectIdSettingsRouteRoute: typeof ConsoleProjectIdSettingsRouteRoute
  ConsoleProjectIdActivityRoute: typeof ConsoleProjectIdActivityRoute
  ConsoleProjectIdFilesRoute: typeof ConsoleProjectIdFilesRoute
  ConsoleProjectIdKeysRoute: typeof ConsoleProjectIdKeysRoute
  ConsoleProjectIdPlaygroundRoute: typeof ConsoleProjectIdPlaygroundRoute
  ConsoleProjectIdSettingsRoute: typeof ConsoleProjectIdSettingsRouteWithChildren
  ConsoleProjectIdWebhooksRoute: typeof ConsoleProjectIdWebhooksRouteWithChildren
  ConsoleProjectIdIndexRoute: typeof ConsoleProjectIdIndexRoute
}

const ConsoleProjectIdRouteRouteChildren: ConsoleProjectIdRouteRouteChildren = {
  ConsoleProjectIdSettingsRouteRoute: ConsoleProjectIdSettingsRouteRoute,
  ConsoleProjectIdActivityRoute: ConsoleProjectIdActivityRoute,
  ConsoleProjectIdFilesRoute: ConsoleProjectIdFilesRoute,
  ConsoleProjectIdKeysRoute: ConsoleProjectIdKeysRoute,
  ConsoleProjectIdPlaygroundRoute: ConsoleProjectIdPlaygroundRoute,
  ConsoleProjectIdSettingsRoute: ConsoleProjectIdSettingsRouteWithChildren,
  ConsoleProjectIdWebhooksRoute: ConsoleProjectIdWebhooksRouteWithChildren,
  ConsoleProjectIdIndexRoute: ConsoleProjectIdIndexRoute,
}

const ConsoleProjectIdRouteRouteWithChildren =
  ConsoleProjectIdRouteRoute._addFileChildren(
    ConsoleProjectIdRouteRouteChildren,
  )

interface ConsoleRouteRouteChildren {
  ConsoleProjectIdRouteRoute: typeof ConsoleProjectIdRouteRouteWithChildren
  ConsoleIndexRoute: typeof ConsoleIndexRoute
}

const ConsoleRouteRouteChildren: ConsoleRouteRouteChildren = {
  ConsoleProjectIdRouteRoute: ConsoleProjectIdRouteRouteWithChildren,
  ConsoleIndexRoute: ConsoleIndexRoute,
}

const ConsoleRouteRouteWithChildren = ConsoleRouteRoute._addFileChildren(
  ConsoleRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConsoleRouteRoute: ConsoleRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  DocsApiRoute: DocsApiRoute,
  DocsApiKeysRoute: DocsApiKeysRoute,
  DocsDeliveryRoute: DocsDeliveryRoute,
  DocsFrameworksRoute: DocsFrameworksRoute,
  DocsGoSdkRoute: DocsGoSdkRoute,
  DocsJavascriptSdkRoute: DocsJavascriptSdkRoute,
  DocsPythonSdkRoute: DocsPythonSdkRoute,
  DocsReactSdkRoute: DocsReactSdkRoute,
  DocsUploadingRoute: DocsUploadingRoute,
  DocsWebhooksRoute: DocsWebhooksRoute,
  V1UploadTokensRoute: V1UploadTokensRoute,
  DocsIndexRoute: DocsIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  FNamespaceSplatRoute: FNamespaceSplatRoute,
  V1FilesSplatRoute: V1FilesSplatRoute,
  V1UploadsUploadIdRoute: V1UploadsUploadIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
